session_name: Zea Engine
suppress_history: false
windows:
  - layout: even-horizontal
    panes:
      - yarn run build:watch
      - yarn run start:watch
  - panes:
      - ${EDITOR} -S
  - panes:
      - shell_command:
          - git fetch
          - git status
