session_name: Zea Engine
suppress_history: false
windows:
  - panes:
      - yarn run dev
  - panes:
      - ${EDITOR} -S
  - panes:
      - shell_command:
          - git fetch
          - git status
