name: E2E testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  testing-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - run: yarn run start &
      - run: yarn run test:e2e --spec cypress/integration/sphere-spec.js
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
