name: Unit testing

on:
  pull_request:
    branches:
      - master

jobs:
  testing-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: yarn install --frozen-lockfile
      - run: yarn test
