name: Unit testing

on:
  pull_request:
    branches:
      - main
      - next
  push:
    branches:
      - main
      - next

jobs:
  testing-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - run: yarn test
