name: E2E testing

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  testing-e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn run start &
      - name: E2E testing
        run: yarn test:e2e
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
