name: E2E testing

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  testing-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: yarn install --frozen-lockfile
      - run: yarn run start &
      - run: yarn run test:e2e
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
